[package]
name = "r_shell"
version = "0.1.0"
authors = ["shaundeveloper <mastercanguro@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
users = "0.11.0"
